# Test
- label: ":docker: Run Docker Tests"
  plugins:
    - docker-compose#v3.0.0:
        run: tests
        config:
          - docker-compose.yml

# Comment out for now
# Tag and release
# - label: ":virtru: Tag Release"
#   command: "buildkite-scripts/scripts/tag-release.sh"
#   branches: "master"
